<?php
/**
 * LicenseRecord
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KeyStack\Manager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Firekeys-stage.com
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KeyStack\Manager\Model;

use \ArrayAccess;
use \KeyStack\Manager\ObjectSerializer;

/**
 * LicenseRecord Class Doc Comment
 *
 * @category Class
 * @package  KeyStack\Manager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LicenseRecord implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LicenseRecord';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'licenseKey' => 'string',
        'status' => 'string',
        'activationsAllowed' => 'int',
        'activationsUsed' => 'int',
        'expiresAt' => '\DateTime',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime',
        'history' => '\KeyStack\Manager\Model\LicenseRecordHistoryInner[]',
        'activations' => '\KeyStack\Manager\Model\ActivationList'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'licenseKey' => null,
        'status' => null,
        'activationsAllowed' => null,
        'activationsUsed' => null,
        'expiresAt' => 'date-time',
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time',
        'history' => null,
        'activations' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'licenseKey' => false,
        'status' => false,
        'activationsAllowed' => false,
        'activationsUsed' => false,
        'expiresAt' => false,
        'createdAt' => false,
        'updatedAt' => false,
        'history' => false,
        'activations' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'licenseKey' => 'licenseKey',
        'status' => 'status',
        'activationsAllowed' => 'activationsAllowed',
        'activationsUsed' => 'activationsUsed',
        'expiresAt' => 'expiresAt',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt',
        'history' => 'history',
        'activations' => 'activations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'licenseKey' => 'setLicenseKey',
        'status' => 'setStatus',
        'activationsAllowed' => 'setActivationsAllowed',
        'activationsUsed' => 'setActivationsUsed',
        'expiresAt' => 'setExpiresAt',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt',
        'history' => 'setHistory',
        'activations' => 'setActivations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'licenseKey' => 'getLicenseKey',
        'status' => 'getStatus',
        'activationsAllowed' => 'getActivationsAllowed',
        'activationsUsed' => 'getActivationsUsed',
        'expiresAt' => 'getExpiresAt',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt',
        'history' => 'getHistory',
        'activations' => 'getActivations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_ACTIVE = 'active';
    public const STATUS_INACTIVE = 'inactive';
    public const STATUS_REVOKED = 'revoked';
    public const STATUS_EXPIRED = 'expired';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_ACTIVE,
            self::STATUS_INACTIVE,
            self::STATUS_REVOKED,
            self::STATUS_EXPIRED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('licenseKey', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('activationsAllowed', $data ?? [], null);
        $this->setIfExists('activationsUsed', $data ?? [], null);
        $this->setIfExists('expiresAt', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
        $this->setIfExists('history', $data ?? [], null);
        $this->setIfExists('activations', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['licenseKey'] === null) {
            $invalidProperties[] = "'licenseKey' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['activationsAllowed'] === null) {
            $invalidProperties[] = "'activationsAllowed' can't be null";
        }
        if (($this->container['activationsAllowed'] < 0)) {
            $invalidProperties[] = "invalid value for 'activationsAllowed', must be bigger than or equal to 0.";
        }

        if ($this->container['activationsUsed'] === null) {
            $invalidProperties[] = "'activationsUsed' can't be null";
        }
        if (($this->container['activationsUsed'] < 0)) {
            $invalidProperties[] = "invalid value for 'activationsUsed', must be bigger than or equal to 0.";
        }

        if ($this->container['expiresAt'] === null) {
            $invalidProperties[] = "'expiresAt' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        if ($this->container['history'] === null) {
            $invalidProperties[] = "'history' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets licenseKey
     *
     * @return string
     */
    public function getLicenseKey()
    {
        return $this->container['licenseKey'];
    }

    /**
     * Sets licenseKey
     *
     * @param string $licenseKey licenseKey
     *
     * @return self
     */
    public function setLicenseKey($licenseKey)
    {
        if (is_null($licenseKey)) {
            throw new \InvalidArgumentException('non-nullable licenseKey cannot be null');
        }
        $this->container['licenseKey'] = $licenseKey;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets activationsAllowed
     *
     * @return int
     */
    public function getActivationsAllowed()
    {
        return $this->container['activationsAllowed'];
    }

    /**
     * Sets activationsAllowed
     *
     * @param int $activationsAllowed activationsAllowed
     *
     * @return self
     */
    public function setActivationsAllowed($activationsAllowed)
    {
        if (is_null($activationsAllowed)) {
            throw new \InvalidArgumentException('non-nullable activationsAllowed cannot be null');
        }

        if (($activationsAllowed < 0)) {
            throw new \InvalidArgumentException('invalid value for $activationsAllowed when calling LicenseRecord., must be bigger than or equal to 0.');
        }

        $this->container['activationsAllowed'] = $activationsAllowed;

        return $this;
    }

    /**
     * Gets activationsUsed
     *
     * @return int
     */
    public function getActivationsUsed()
    {
        return $this->container['activationsUsed'];
    }

    /**
     * Sets activationsUsed
     *
     * @param int $activationsUsed activationsUsed
     *
     * @return self
     */
    public function setActivationsUsed($activationsUsed)
    {
        if (is_null($activationsUsed)) {
            throw new \InvalidArgumentException('non-nullable activationsUsed cannot be null');
        }

        if (($activationsUsed < 0)) {
            throw new \InvalidArgumentException('invalid value for $activationsUsed when calling LicenseRecord., must be bigger than or equal to 0.');
        }

        $this->container['activationsUsed'] = $activationsUsed;

        return $this;
    }

    /**
     * Gets expiresAt
     *
     * @return \DateTime
     */
    public function getExpiresAt()
    {
        return $this->container['expiresAt'];
    }

    /**
     * Sets expiresAt
     *
     * @param \DateTime $expiresAt expiresAt
     *
     * @return self
     */
    public function setExpiresAt($expiresAt)
    {
        if (is_null($expiresAt)) {
            throw new \InvalidArgumentException('non-nullable expiresAt cannot be null');
        }
        $this->container['expiresAt'] = $expiresAt;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt updatedAt
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            throw new \InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }

    /**
     * Gets history
     *
     * @return \KeyStack\Manager\Model\LicenseRecordHistoryInner[]
     */
    public function getHistory()
    {
        return $this->container['history'];
    }

    /**
     * Sets history
     *
     * @param \KeyStack\Manager\Model\LicenseRecordHistoryInner[] $history history
     *
     * @return self
     */
    public function setHistory($history)
    {
        if (is_null($history)) {
            throw new \InvalidArgumentException('non-nullable history cannot be null');
        }
        $this->container['history'] = $history;

        return $this;
    }

    /**
     * Gets activations
     *
     * @return \KeyStack\Manager\Model\ActivationList|null
     */
    public function getActivations()
    {
        return $this->container['activations'];
    }

    /**
     * Sets activations
     *
     * @param \KeyStack\Manager\Model\ActivationList|null $activations activations
     *
     * @return self
     */
    public function setActivations($activations)
    {
        if (is_null($activations)) {
            throw new \InvalidArgumentException('non-nullable activations cannot be null');
        }
        $this->container['activations'] = $activations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


