<?php
/**
 * ActivationRecordTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KeyStack\Manager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Firekeys-stage.com
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace KeyStack\Manager\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ActivationRecordTest Class Doc Comment
 *
 * @category    Class
 * @description ActivationRecord
 * @package     KeyStack\Manager
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ActivationRecordTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ActivationRecord"
     */
    public function testActivationRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "activationId"
     */
    public function testPropertyActivationId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "siteUrl"
     */
    public function testPropertySiteUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pluginVersion"
     */
    public function testPropertyPluginVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phpVersion"
     */
    public function testPropertyPhpVersion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
