<?php
/**
 * ManagerApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  KeyStack\Manager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Firekeys-stage.com
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KeyStack\Manager\Test\Api;

use \KeyStack\Manager\Configuration;
use \KeyStack\Manager\ApiException;
use \KeyStack\Manager\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ManagerApiTest Class Doc Comment
 *
 * @category Class
 * @package  KeyStack\Manager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ManagerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addManifestRecord
     *
     * .
     *
     */
    public function testAddManifestRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createLicense
     *
     * .
     *
     */
    public function testCreateLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteActivation
     *
     * .
     *
     */
    public function testDeleteActivation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteLicense
     *
     * .
     *
     */
    public function testDeleteLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteManifestRecord
     *
     * .
     *
     */
    public function testDeleteManifestRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getActivations
     *
     * .
     *
     */
    public function testGetActivations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllLicenses
     *
     * .
     *
     */
    public function testGetAllLicenses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLicense
     *
     * .
     *
     */
    public function testGetLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listManifestRecords
     *
     * .
     *
     */
    public function testListManifestRecords()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readManifestRecord
     *
     * .
     *
     */
    public function testReadManifestRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateLicense
     *
     * .
     *
     */
    public function testUpdateLicense()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
